# Generated by Django 3.1.2 on 2020-10-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField(max_length=150)),
                ('city', models.TextField(max_length=400)),
                ('plz', models.TextField(max_length=15)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
