# Generated by Django 3.1.2 on 2020-10-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20201031_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationinformation',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='administrationinformation',
            name='plz',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='administrationinformation',
            name='street',
            field=models.CharField(max_length=80),
        ),
    ]
