# Generated by Django 3.1.2 on 2020-11-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_administrationinformation_telefon_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationinformation',
            name='plz',
            field=models.CharField(max_length=4),
        ),
    ]
