# Generated by Django 3.1.2 on 2020-11-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20201108_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationinformation',
            name='name',
            field=models.CharField(default='random', max_length=100),
            preserve_default=False,
        ),
    ]
