# Generated by Django 3.1.2 on 2020-11-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_administrationinformation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationinformation',
            name='telefon_number',
            field=models.CharField(max_length=15),
        ),
    ]
