# Generated by Django 3.1.2 on 2021-01-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20201120_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationinformation',
            name='telefon_number',
            field=models.CharField(max_length=30),
        ),
    ]
