# Generated by Django 3.1.2 on 2021-01-06 13:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20201120_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationinformation',
            name='telefon_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
