# Generated by Django 3.1.2 on 2021-01-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20210106_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationinformation',
            name='telefon_number',
            field=models.CharField(max_length=30),
        ),
    ]
