# Generated by Django 3.1.2 on 2020-10-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModalitiesInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150)),
                ('description', models.TextField(max_length=400)),
                ('status', models.TextField(max_length=15)),
            ],
        ),
    ]
