# Generated by Django 3.1.2 on 2020-10-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalitiesinformation',
            name='status',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='modalitiesinformation',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
