# Generated by Django 3.1.2 on 2020-11-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modalities', '0002_auto_20201108_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalitiesinformation',
            name='associate_location',
        ),
    ]
