# Generated by Django 3.1.2 on 2020-11-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalities', '0004_modalitiesinformation_associate_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalitiesinformation',
            name='associate_location',
            field=models.TextField(),
        ),
    ]
