# Generated by Django 3.1.2 on 2020-11-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalities', '0005_auto_20201121_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalitiesinformation',
            name='associate_location',
            field=models.CharField(max_length=500),
        ),
    ]
