# Generated by Django 3.1.2 on 2020-11-21 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20201120_1133'),
        ('modalities', '0007_remove_modalitiesinformation_associate_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalitiesinformation',
            name='associate_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.administrationinformation'),
            preserve_default=False,
        ),
    ]
