# Generated by Django 3.1.2 on 2020-11-21 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20201120_1133'),
        ('modalities', '0009_auto_20201121_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalitiesinformation',
            name='associate_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.administrationinformation'),
        ),
    ]
