# Generated by Django 3.1.2 on 2020-11-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalities', '0010_auto_20201121_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalitiesinformation',
            name='title',
            field=models.CharField(choices=[('CR', 'Computerradiografie'), ('CT', 'Computertomografie'), ('US', 'Ultraschall'), ('ES', 'Endoskopie'), ('DX', 'Digitale Radiografie'), ('MG', 'Mammografie')], max_length=150),
        ),
    ]
