# Generated by Django 3.1.2 on 2021-01-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalities', '0011_auto_20201126_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalitiesinformation',
            name='title',
            field=models.CharField(choices=[('CR', ' Computerradiografie '), ('CT', 'Computertomografie'), ('US', 'Ultraschall'), ('ES', 'Endoskopie'), ('DX', 'Digitale Radiografie'), ('MG', 'Mammografie')], max_length=150),
        ),
    ]
