# Generated by Django 3.1.2 on 2020-11-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorklistInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_procedure_step_start_date', models.CharField(max_length=8)),
                ('scheduled_procedure_step_start_time', models.CharField(max_length=12)),
                ('modality', models.CharField(max_length=8)),
                ('scheduled_performing_physician_s_name', models.CharField(max_length=50)),
                ('patient_s_name', models.CharField(max_length=50)),
                ('patient_id', models.CharField(max_length=64)),
                ('scheduled_procedure_step_description', models.CharField(max_length=64)),
                ('patient_s_birth_date', models.CharField(max_length=8)),
                ('patient_s_sex', models.CharField(max_length=4)),
            ],
        ),
    ]
