# Generated by Django 3.1.2 on 2020-11-22 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_procedure_step_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
