# Generated by Django 3.1.2 on 2020-11-22 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0003_auto_20201122_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_procedure_step_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
