# Generated by Django 3.1.2 on 2020-11-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0003_auto_20201118_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_procedure_step_description',
            field=models.CharField(max_length=64),
        ),
    ]
