# Generated by Django 3.1.2 on 2020-11-22 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0004_auto_20201122_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_procedure_step_start_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 22, 21, 52, 44, 908026)),
        ),
    ]
