# Generated by Django 3.1.2 on 2020-11-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0004_auto_20201118_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklistinformation',
            name='patient_s_name',
        ),
        migrations.RemoveField(
            model_name='worklistinformation',
            name='scheduled_station_ae_title',
        ),
    ]
