# Generated by Django 3.1.2 on 2020-11-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0005_auto_20201119_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklistinformation',
            name='modality',
        ),
    ]
