# Generated by Django 3.1.2 on 2020-11-22 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0005_auto_20201122_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_procedure_step_start_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 22, 22, 41, 43, 629771)),
        ),
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_procedure_step_start_time',
            field=models.DateField(default=datetime.datetime(2020, 11, 22, 22, 41, 43, 629868)),
        ),
    ]
