# Generated by Django 3.1.2 on 2020-11-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0006_auto_20201122_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_procedure_step_start_date',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_procedure_step_start_time',
            field=models.CharField(max_length=12),
        ),
    ]
