# Generated by Django 3.1.2 on 2020-11-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0007_auto_20201122_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_procedure_step_start_date',
            field=models.CharField(max_length=100),
        ),
    ]
