# Generated by Django 3.1.2 on 2020-11-24 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modalities', '0010_auto_20201121_2128'),
        ('worklists', '0009_auto_20201122_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklistinformation',
            name='modality',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='modalities.modalitiesinformation'),
            preserve_default=False,
        ),
    ]
