# Generated by Django 3.1.2 on 2020-11-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0010_worklistinformation_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklistinformation',
            name='patient_s_name',
            field=models.CharField(default='name of person', max_length=100),
            preserve_default=False,
        ),
    ]
