# Generated by Django 3.1.2 on 2020-11-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0011_worklistinformation_patient_s_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_performing_physician_s_name',
            field=models.CharField(choices=[('dr1', 'Dr. Thomas Bürkle'), ('dr2', 'Dr. Michael Lehmann'), ('dr3', 'Dr. Stephan Nüssli')], max_length=80),
        ),
    ]
