# Generated by Django 3.1.2 on 2020-11-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0012_auto_20201124_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_performing_physician_s_name',
            field=models.CharField(max_length=80),
        ),
    ]
