# Generated by Django 3.1.2 on 2020-11-26 22:11

from django.db import migrations, models
import worklists.models


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0014_auto_20201124_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_procedure_step_start_date',
            field=models.CharField(max_length=100, validators=[worklists.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_procedure_step_start_time',
            field=models.CharField(max_length=12, validators=[worklists.models.validate_time]),
        ),
    ]
