# Generated by Django 3.1.2 on 2020-11-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0015_auto_20201126_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_performing_physician_s_name',
            field=models.CharField(choices=[('dr1', 'Dr. Thomas Burkle'), ('dr2', 'Dr. Michael Lehmann'), ('dr3', 'Dr. Stephan Nuessli')], max_length=80),
        ),
    ]
