# Generated by Django 3.1.2 on 2020-12-08 17:28

from django.db import migrations, models
import worklists.models


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0016_auto_20201129_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_procedure_step_start_date',
            field=models.DateField(validators=[worklists.models.validate_date]),
        ),
    ]
