# Generated by Django 3.1.2 on 2021-01-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0018_auto_20201208_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_procedure_step_description',
            field=models.CharField(max_length=500),
        ),
    ]
