# Generated by Django 3.1.5 on 2021-01-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklists', '0021_auto_20210117_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklistinformation',
            name='scheduled_performing_physician_s_name',
            field=models.CharField(choices=[('dr1', 'Dr. Stephan Weingartner'), ('dr2', 'Dr. Thomas Anderson'), ('dr3', 'Dr. Marvin Spengler')], max_length=80),
        ),
    ]
