# Generated by Django 3.1.2 on 2020-10-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='title',
            field=models.CharField(choices=[('male', 'Herr'), ('female', 'Frau')], max_length=6),
        ),
    ]
