# Generated by Django 3.1.2 on 2020-10-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patientinformation_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinformation',
            name='name',
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='first_name',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='second_name',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
