# Generated by Django 3.1.2 on 2020-10-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20201027_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='second_name',
            field=models.CharField(max_length=50),
        ),
    ]
