# Generated by Django 3.1.2 on 2020-10-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20201027_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='birthdate',
            field=models.DateField(auto_now=True),
        ),
    ]
