# Generated by Django 3.1.2 on 2020-10-31 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_auto_20201031_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinformation',
            old_name='languagge',
            new_name='languag_ge',
        ),
    ]
