# Generated by Django 3.1.2 on 2020-10-31 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_auto_20201031_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinformation',
            old_name='languag_ge',
            new_name='languag_e',
        ),
    ]
