# Generated by Django 3.1.2 on 2020-11-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_auto_20201031_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinformation',
            old_name='sprache',
            new_name='language',
        ),
    ]
