# Generated by Django 3.1.2 on 2020-11-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_auto_20201101_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinformation',
            old_name='sprache',
            new_name='language',
        ),
    ]
