# Generated by Django 3.1.2 on 2020-11-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_auto_20201101_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinformation',
            old_name='adresse',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patientinformation',
            old_name='geburtsdatum',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='patientinformation',
            old_name='plz',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='patientinformation',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patientinformation',
            old_name='vorname',
            new_name='second_name',
        ),
    ]
