# Generated by Django 3.1.2 on 2020-11-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_auto_20201101_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='number',
            field=models.IntegerField(default='58'),
            preserve_default=False,
        ),
    ]
