# Generated by Django 3.1.2 on 2020-11-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_auto_20201112_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='city',
            field=models.CharField(default='city', max_length=25),
            preserve_default=False,
        ),
    ]
