# Generated by Django 3.1.2 on 2020-11-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_patientinformation_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='language',
            field=models.CharField(max_length=50),
        ),
    ]
