# Generated by Django 3.1.2 on 2020-12-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_auto_20201126_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='study',
            field=models.ImageField(default='some', upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
