# Generated by Django 3.1.2 on 2020-12-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0025_patientinformation_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinformation',
            name='study',
        ),
    ]
